/*
 * generated by Xtext 2.25.0
 */
package iotecs.ui;

import com.google.inject.Injector;
import iotecs.ui.internal.IotecsActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IoTECSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(IotecsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		IotecsActivator activator = IotecsActivator.getInstance();
		return activator != null ? activator.getInjector(IotecsActivator.IOTECS_IOTECS) : null;
	}

}
