/*
 * generated by Xtext 2.25.0
 */
package iotecs.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import iotecs.IoTECSRuntimeModule;
import iotecs.IoTECSStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class IoTECSIdeSetup extends IoTECSStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new IoTECSRuntimeModule(), new IoTECSIdeModule()));
	}
	
}
