/*
 * generated by Xtext 2.25.0
 */
package iotecs.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import iotecs.ide.contentassist.antlr.internal.InternalIoTECSParser;
import iotecs.services.IoTECSGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class IoTECSParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(IoTECSGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, IoTECSGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getElementAccess().getAlternatives(), "rule__Element__Alternatives");
			builder.put(grammarAccess.getSpeedAccess().getAlternatives(), "rule__Speed__Alternatives");
			builder.put(grammarAccess.getTimeUnitAccess().getAlternatives(), "rule__TimeUnit__Alternatives");
			builder.put(grammarAccess.getTimeUnitForWorkloadAccess().getAlternatives(), "rule__TimeUnitForWorkload__Alternatives");
			builder.put(grammarAccess.getPayloadUnitAccess().getAlternatives(), "rule__PayloadUnit__Alternatives");
			builder.put(grammarAccess.getProtocolAccess().getAlternatives(), "rule__Protocol__Alternatives");
			builder.put(grammarAccess.getPlatformTypeAccess().getAlternatives(), "rule__PlatformType__Alternatives");
			builder.put(grammarAccess.getPlatformAccess().getGroup(), "rule__Platform__Group__0");
			builder.put(grammarAccess.getPlatformAccess().getGroup_7(), "rule__Platform__Group_7__0");
			builder.put(grammarAccess.getPlatformAccess().getGroup_8(), "rule__Platform__Group_8__0");
			builder.put(grammarAccess.getPlatformAccess().getGroup_9(), "rule__Platform__Group_9__0");
			builder.put(grammarAccess.getSimulatorAccess().getGroup(), "rule__Simulator__Group__0");
			builder.put(grammarAccess.getCloudAccess().getGroup(), "rule__Cloud__Group__0");
			builder.put(grammarAccess.getCloudAccess().getGroup_7(), "rule__Cloud__Group_7__0");
			builder.put(grammarAccess.getCloudAccess().getGroup_8(), "rule__Cloud__Group_8__0");
			builder.put(grammarAccess.getSimulationNodeAccess().getGroup(), "rule__SimulationNode__Group__0");
			builder.put(grammarAccess.getSimulationNodesAccess().getGroup(), "rule__SimulationNodes__Group__0");
			builder.put(grammarAccess.getEdgeDeviceAccess().getGroup(), "rule__EdgeDevice__Group__0");
			builder.put(grammarAccess.getEdgeDevicesAccess().getGroup(), "rule__EdgeDevices__Group__0");
			builder.put(grammarAccess.getDevicesAccess().getGroup(), "rule__Devices__Group__0");
			builder.put(grammarAccess.getDeviceAccess().getGroup(), "rule__Device__Group__0");
			builder.put(grammarAccess.getIPAccess().getGroup(), "rule__IP__Group__0");
			builder.put(grammarAccess.getModelAccess().getElementsAssignment(), "rule__Model__ElementsAssignment");
			builder.put(grammarAccess.getPlatformAccess().getNameAssignment_1(), "rule__Platform__NameAssignment_1");
			builder.put(grammarAccess.getPlatformAccess().getTypeAssignment_4(), "rule__Platform__TypeAssignment_4");
			builder.put(grammarAccess.getPlatformAccess().getNetworkAdapterAssignment_6(), "rule__Platform__NetworkAdapterAssignment_6");
			builder.put(grammarAccess.getPlatformAccess().getLocationAssignment_7_1(), "rule__Platform__LocationAssignment_7_1");
			builder.put(grammarAccess.getPlatformAccess().getUserAssignment_7_3(), "rule__Platform__UserAssignment_7_3");
			builder.put(grammarAccess.getPlatformAccess().getPasswordAssignment_7_5(), "rule__Platform__PasswordAssignment_7_5");
			builder.put(grammarAccess.getPlatformAccess().getCPUAssignment_8_1(), "rule__Platform__CPUAssignment_8_1");
			builder.put(grammarAccess.getPlatformAccess().getMemoryAssignment_8_3(), "rule__Platform__MemoryAssignment_8_3");
			builder.put(grammarAccess.getPlatformAccess().getIpVMAssignment_9_1(), "rule__Platform__IpVMAssignment_9_1");
			builder.put(grammarAccess.getPlatformAccess().getUserVMAssignment_9_3(), "rule__Platform__UserVMAssignment_9_3");
			builder.put(grammarAccess.getPlatformAccess().getPasswordVMAssignment_9_5(), "rule__Platform__PasswordVMAssignment_9_5");
			builder.put(grammarAccess.getSimulatorAccess().getDurationAssignment_3(), "rule__Simulator__DurationAssignment_3");
			builder.put(grammarAccess.getSimulatorAccess().getDurationUnitAssignment_4(), "rule__Simulator__DurationUnitAssignment_4");
			builder.put(grammarAccess.getSimulatorAccess().getStepAssignment_6(), "rule__Simulator__StepAssignment_6");
			builder.put(grammarAccess.getSimulatorAccess().getStepUnitAssignment_7(), "rule__Simulator__StepUnitAssignment_7");
			builder.put(grammarAccess.getSimulatorAccess().getSimulationNodesAssignment_10(), "rule__Simulator__SimulationNodesAssignment_10");
			builder.put(grammarAccess.getCloudAccess().getNameAssignment_1(), "rule__Cloud__NameAssignment_1");
			builder.put(grammarAccess.getCloudAccess().getIpAssignment_4(), "rule__Cloud__IpAssignment_4");
			builder.put(grammarAccess.getCloudAccess().getPortAssignment_6(), "rule__Cloud__PortAssignment_6");
			builder.put(grammarAccess.getCloudAccess().getUsrnameAssignment_7_1(), "rule__Cloud__UsrnameAssignment_7_1");
			builder.put(grammarAccess.getCloudAccess().getPasswordAssignment_7_3(), "rule__Cloud__PasswordAssignment_7_3");
			builder.put(grammarAccess.getCloudAccess().getWorkloadAssignment_7_5(), "rule__Cloud__WorkloadAssignment_7_5");
			builder.put(grammarAccess.getCloudAccess().getWorkloadUnitAssignment_7_6(), "rule__Cloud__WorkloadUnitAssignment_7_6");
			builder.put(grammarAccess.getCloudAccess().getNetworkAdapterAssignment_8_1(), "rule__Cloud__NetworkAdapterAssignment_8_1");
			builder.put(grammarAccess.getSimulationNodeAccess().getNameAssignment_1(), "rule__SimulationNode__NameAssignment_1");
			builder.put(grammarAccess.getSimulationNodeAccess().getPlatformAssignment_4(), "rule__SimulationNode__PlatformAssignment_4");
			builder.put(grammarAccess.getSimulationNodeAccess().getEdgeDevicesAssignment_7(), "rule__SimulationNode__EdgeDevicesAssignment_7");
			builder.put(grammarAccess.getSimulationNodesAccess().getSnAssignment_0(), "rule__SimulationNodes__SnAssignment_0");
			builder.put(grammarAccess.getSimulationNodesAccess().getNAssignment_2(), "rule__SimulationNodes__NAssignment_2");
			builder.put(grammarAccess.getEdgeDeviceAccess().getNameAssignment_1(), "rule__EdgeDevice__NameAssignment_1");
			builder.put(grammarAccess.getEdgeDeviceAccess().getProtocolAssignment_4(), "rule__EdgeDevice__ProtocolAssignment_4");
			builder.put(grammarAccess.getEdgeDeviceAccess().getSpeedAssignment_6(), "rule__EdgeDevice__SpeedAssignment_6");
			builder.put(grammarAccess.getEdgeDeviceAccess().getCloudAssignment_8(), "rule__EdgeDevice__CloudAssignment_8");
			builder.put(grammarAccess.getEdgeDeviceAccess().getWorkloadAssignment_10(), "rule__EdgeDevice__WorkloadAssignment_10");
			builder.put(grammarAccess.getEdgeDeviceAccess().getWorkloadUnitAssignment_11(), "rule__EdgeDevice__WorkloadUnitAssignment_11");
			builder.put(grammarAccess.getEdgeDeviceAccess().getDevicesAssignment_14(), "rule__EdgeDevice__DevicesAssignment_14");
			builder.put(grammarAccess.getEdgeDevicesAccess().getSaAssignment_0(), "rule__EdgeDevices__SaAssignment_0");
			builder.put(grammarAccess.getEdgeDevicesAccess().getNAssignment_2(), "rule__EdgeDevices__NAssignment_2");
			builder.put(grammarAccess.getDevicesAccess().getAAssignment_0(), "rule__Devices__AAssignment_0");
			builder.put(grammarAccess.getDevicesAccess().getNAssignment_2(), "rule__Devices__NAssignment_2");
			builder.put(grammarAccess.getDeviceAccess().getNameAssignment_1(), "rule__Device__NameAssignment_1");
			builder.put(grammarAccess.getDeviceAccess().getPeriodAssignment_4(), "rule__Device__PeriodAssignment_4");
			builder.put(grammarAccess.getDeviceAccess().getPayloadAssignment_6(), "rule__Device__PayloadAssignment_6");
			builder.put(grammarAccess.getDeviceAccess().getPayloadUnitAssignment_7(), "rule__Device__PayloadUnitAssignment_7");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private IoTECSGrammarAccess grammarAccess;

	@Override
	protected InternalIoTECSParser createParser() {
		InternalIoTECSParser result = new InternalIoTECSParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public IoTECSGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IoTECSGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
