/*
 * generated by Xtext 2.25.0
 */
package iotecs.ui.tests;

import com.google.inject.Injector;
import iotecs.ui.internal.IotecsActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class IoTECSUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IotecsActivator.getInstance().getInjector("iotecs.IoTECS");
	}

}
