/*
 * generated by Xtext 2.25.0
 */
package iotecs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IoTECSUiModule extends AbstractIoTECSUiModule {

	public IoTECSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
